apiVersion: v1
kind: ConfigMap
metadata:
  name: locator
data:
  start.sh: |
    #!/bin/bash

    #Clean up stale PID from container exit
    rm -f /locator/data/vf.gf.locator.pid

    gfsh start locator --name=${HOSTNAME} --port=${GEODE_LOCATOR_PORT} --J=-Dgemfire.distributed-system-id=${GEODE_CLUSTER_ID} --J=-Dgemfire.remote-locators=${HOSTNAME}.${GEODE_REMOTE_LOCATOR_HOST}.geode-cluster-${GEODE_REMOTE_CLUSTER_ID}.svc.cluster.local[${GEODE_REMOTE_LOCATOR_PORT}] --dir=/locator/data

    while true; do
      sleep 10
    done
