apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{.Values.geode_locator.name}}-site{{.Values.geode_cluster_id}}-service
    role: locator
  name: {{.Values.geode_locator.name}}-site{{.Values.geode_cluster_id}}-service
spec:
  ports:
  - name: {{.Values.geode_locator.port_name}}
    port: {{.Values.geode_locator.port}}
    targetPort: {{.Values.geode_locator.port}}
    protocol: TCP
  clusterIP: None
  selector:
    geode-locator: "true"
