apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{.Values.geode_server.name}}-site{{.Values.geode_cluster_id}}-service
    role: server
  name: {{.Values.geode_server.name}}-site{{.Values.geode_cluster_id}}-service
spec:
  type: NodePort
  ports:
  - name: {{.Values.geode_server.port_name}}
    port: {{.Values.geode_server.port}}
    targetPort: {{.Values.geode_server.port}}
    nodePort: {{.Values.geode_server.port}}
    protocol: TCP
  - name: {{.Values.receiver.port_name}}
    port: {{.Values.receiver.port}}
    targetPort: {{.Values.receiver.port}}
    nodePort: {{.Values.receiver.port}}
    protocol: TCP
  selector:
    geode-server: "true"
