apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.geode_server.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.geode_server.name}}
  serviceName: {{.Values.geode_server.name}}-site{{.Values.geode_cluster_id}}-service
  replicas: 2
  template:
    metadata:
      labels:
        app: {{.Values.geode_server.name}}
        geode-server: "true"
        role: server
    spec:
      containers:
      - name: server
        image: {{.Values.geode_server.image}}
        imagePullPolicy: Always
        command:
        - bash
        - /config/start.sh
        ports:
          - containerPort: {{.Values.geode_server.port}}
            name: {{.Values.geode_server.port_name}}
            protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
        env:
          - name: GEODE_LOCATOR_HOST
            value: "{{.Values.geode_locator.name}}-site{{.Values.geode_cluster_id}}-service"
          - name: GEODE_LOCATOR_PORT
            value: "{{.Values.geode_locator.port}}"
          - name: GEODE_CLUSTER_ID
            value: "{{.Values.geode_cluster_id}}"
          - name: GEODE_REMOTE_CLUSTER_ID
            value: "{{.Values.geode_remote_cluster_id}}"
          - name: GEODE_RECEIVER_SERVICE_NAME
            value: "{{.Values.geode_server.name}}-site{{.Values.geode_cluster_id}}-service"
          - name: GEODE_RECEIVER_SERVICE_PORT
            value: "{{.Values.geode_server.receiver_port}}"
      volumes:
      - name: config
        configMap:
          name: "server"
